version: '3.7'

services:
  mule:
    container_name: ${PROJECT_NAME}_in-docker
    restart: on-failure
    build: .

    volumes:
      - $PWD/apps:/opt/mule/apps
      - $PWD/logs:/opt/mule/logs
      - $PWD/domains:/opt/mule/domains
      - $PWD/conf:/opt/mule/conf

    ports:
      - "80:8181"


